### ISSUE TITLE
Respect `xref-find-definitions-other-window`

### ISSUE THREAD

**Issue by cocreature** [alexmurray/ivy-xref#7] opened 2018-04-04 08:13 UTC
`ivy-xref-show-xrefs` seems to ignore the `display-action` parameter that `xref-find-definitions-other-window` sets in the `alist`. It would be nice to support this.

**Comment by alexmurray** [comment] 2018-04-04 12:55
This should be handled automatically since we first call the original `xref--show-xref-buffer` which saves the properties from `alist` to `xref--original-window` and `xref--original-window-intent` - then we display the xref by calling `xref--show-location` which ends up calling `xref--show-pos-in-buf` which finally respects these values.

This works for me - but if it doesn't work for you please can you provide details on how I can try and reproduce the issue so I can try and make sure it works for you too?

**Comment by cocreature** [comment] 2018-04-04 16:01
It looks like the problem is not `xref-find-definitions-other-window` (not sure what made me think that was the problem initially) but that something seems to have changed in Emacs 26 which messes up windows. Here’s a screen recording to demonstrate the problem: https://purelyfunctional.org/downloads/xref-windows-problems.mp4

**Comment by aslpavel** [comment] 2018-05-25 12:23
I have exactly same problem as @cocreature:
- basically after jump I have two frames open, one contains destination and other just random buffer
- for now I've added `(add-hook 'xref-after-jump-hook #'delete-other-windows)` but its far from perfect, because this way I cannot use more than one frame

**Comment by alexmurray** [comment] 2018-06-01 05:41
Closed since #11 is now merged.

**Closed by alexmurray** 2018-06-01 05:41 UTC
